// <auto-generated />
using System;
using CssWebApi.CssWebApi.Features.EfSample.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CssWebApi.CssWebApi.Features.EfSample.EfCore.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20240610161312_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");

            modelBuilder.Entity("CssWebApi.CssWebApi.Features.EfSample.EfCore.SampleEfCoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("STRING(36)");

                    b.Property<string>("InstitutionUniversalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("STRING(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("STRING(256)");

                    b.HasKey("Id");

                    b.ToTable("SampleEntity", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
